### ISSUE TITLE
"Robotics" - styling and content issues

### ISSUE THREAD

**Issue by ygord-vayyar** [Vayyar/vayyar-wp#8]
- Too much padding above & below the "Robotics" title
- Too much line space in subtitle, "Personal Robots Home & Commercial"
- "i.e. elderly care" should read "e.g. elderly care"
- Verbose: there is a section for "Contact us for details and packages", and then a little further down the page is a section called "Get started with Vayyar", which gives details of the Basic and Advanced packages. Both these sections (Contact us... and Get started...) have links to the Contact form. Are they both needed?

**Comment by migkapa** [comment]
This points are done:

- Too much padding above & below the "Robotics" title
- Too much line space in subtitle, "Personal Robots Home & Commercial"
- "i.e. elderly care" should read "e.g. elderly care"

@ygord-vayyar 
Regarding the last one, if you're asking about improving it, yes there is better choices rather than that. That is what the static site had before. So let's talk with @noamhoze also if we should change something there.

**Comment by noamhoze** [comment]
@ygord-vayyar, regarding the verbosity it's like this from a marketing point of view so that should stay as it is.
